name: Revert on Failure

on:
  push:
    branches:
      - master

jobs:
  check-and-revert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Unit test
        run: npm test

      - name: Revert changes if actions fail
        if: failure()
        run: |
          git reset --hard HEAD~1
          git push --force
